# Generated by Django 3.2.8 on 2021-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockist',
            name='stockist_channel',
            field=models.CharField(choices=[(1, 'Pureplay Ecomm'), (2, 'Physical Only'), (3, 'Multi-Channel'), (4, 'Marketplace')], max_length=30),
        ),
    ]
