# Generated by Django 3.2.8 on 2021-11-25 09:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('jewellery', 'Jewellery'), ('leather_accessories', 'Leather Accessories'), ('blankets', 'Blankets'), ('knitted_accessories', 'Knitted Accessories'), ('clothing', 'Clothing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='purchasing_currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stockist_channel',
            field=models.CharField(choices=[('Pureplay Ecomm', 'Pureplay Ecomm'), ('Physical Only', 'Physical Only'), ('Multi-Channel', 'Multi-Channel'), ('Marketplace', 'Marketplace')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stockist_market',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Women', 'Women'), ('Home', 'Home'), ('Jewellery', 'Jewellery'), ('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Gifting', 'Gifting')], max_length=100),
        ),
    ]
