# Generated by Django 3.2.8 on 2021-11-10 10:46

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_stockist_stockist_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockist_name', models.CharField(blank=True, max_length=60, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=60, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('accounts_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('accounts_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('address_1', models.CharField(blank=True, max_length=80, null=True)),
                ('address_2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=35, null=True)),
                ('county_or_state', models.CharField(blank=True, max_length=35, null=True)),
                ('postcode', models.CharField(blank=True, max_length=12, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('purchasing_currency', models.CharField(choices=[(1, 'GBP'), (2, 'EUR')], max_length=30)),
                ('stockist_channel', models.CharField(choices=[(1, 'Pureplay Ecomm'), (2, 'Physical Only'), (3, 'Multi-Channel'), (4, 'Marketplace')], max_length=30)),
                ('stockist_market', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Women'), (2, 'Home'), (3, 'Jewellery'), (4, 'Accessories'), (5, 'Clothing'), (6, 'Gifting')], max_length=30)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[('jewellery', 'Jewellery'), ('leather_accessories', 'Leather Accessories'), ('blankets', 'Blankets'), ('knitted_accessories', 'Knitted Accessories'), ('clothing', 'Clothing')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockist',
            name='stockist',
        ),
    ]
