# Generated by Django 3.2.8 on 2021-11-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_stockist_stockist_channel'),
        ('products', '0002_alter_category_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('buyer_name', models.CharField(max_length=60)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.CharField(max_length=200)),
                ('accounts_phone', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('town_or_city', models.CharField(max_length=35)),
                ('county_or_state', models.CharField(max_length=35)),
                ('postcode', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateTimeField(editable=False)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='profiles.stockist')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem_qty', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
