# Generated by Django 3.2.8 on 2021-11-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_stockist_stockist_channel'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='stockist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.stockist'),
        ),
    ]
