# Generated by Django 3.2.8 on 2021-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='lg_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='m_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='sm_n',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='xl_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='xs_l_one_size',
            field=models.IntegerField(default=0),
        ),
    ]
