# Generated by Django 3.2.8 on 2021-11-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211110_1146'),
        ('checkout', '0002_auto_20211109_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stockist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.userprofile'),
        ),
    ]
