# Generated by Django 3.2.8 on 2021-11-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_rename_stockist_name_userprofile_stockist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=90)),
                ('testimonial', models.TextField(max_length=300)),
                ('stockist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
