# Generated by Django 3.2.8 on 2021-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_category', models.CharField(choices=[('Delivery', 'Delivery'), ('Ordering', 'Ordering'), ('Payments', 'Payments'), ('Exclusivity', 'Exclusivity'), ('Marketing', 'Marketing')], max_length=14)),
                ('question', models.TextField(max_length=250)),
                ('answer', models.TextField(max_length=250)),
            ],
        ),
    ]
