# Generated by Django 3.2.8 on 2021-10-12 12:28

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=90)),
                ('product_sku', models.CharField(max_length=90)),
                ('product_description', models.TextField()),
                ('product_is_bestseller', models.BooleanField(default=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rrp_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('friendly_name', models.CharField(max_length=90)),
                ('product_categories', models.CharField(choices=[('jewellery', 'Jewellery'), ('leather_accessories', 'Leather Accessories'), ('blankets', 'Blankets'), ('knitted_accessories', 'Knitted Accessories'), ('clothing', 'Clothing')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rings',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('jewellery_properties', models.CharField(choices=[('SR', 'silver'), ('GD', 'gold')], max_length=2)),
                ('rings_sizes', multiselectfield.db.fields.MultiSelectField(choices=[('6', 'L'), ('7', 'N'), ('8', 'P'), ('9', 'S'), ('10', 'U')], default='6', max_length=2)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('friendly_name', models.CharField(max_length=90)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype'),
        ),
    ]
