# Generated by Django 3.2.8 on 2021-11-20 12:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Earrings'), (2, 'Pendants / Necklaces'), (3, 'Rings'), (4, 'Bracelets / Bangles'), (5, 'Tops'), (6, 'Knitwear'), (7, 'Skirts'), (8, 'Shorts'), (9, 'Trousers'), (10, 'Jeans'), (11, 'Ponchos'), (12, 'Beanie Hats'), (13, 'Scarves'), (14, 'Beanie Hats'), (15, 'Leather Bags'), (16, 'Beltbags / Bumbags'), (17, 'Wallets / Purses'), (18, 'Belts'), (19, 'Blankets')], default='Earrings', max_length=20, verbose_name='Type'),
        ),
    ]
