# Generated by Django 3.2.8 on 2021-10-12 14:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_properties',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SS', 'sterling silver'), ('GP', 'gold plated'), ('PW', 'wool'), ('HC', 'hand crafted'), ('FP', 'fairly produced'), ('LI', 'low environmental impact')], default='FP', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('universal_size_type', 'one size'), ('jewellery_size_type', 'jewellery sizes'), ('clothing_size_type', 'clothing sizes')], default='universal_size_type', max_length=30),
        ),
    ]
