# Generated by Django 3.2.8 on 2021-10-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211012_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rings',
            new_name='Ring',
        ),
        migrations.RenameField(
            model_name='ring',
            old_name='rings_sizes',
            new_name='ring_sizes',
        ),
    ]
