# Generated by Django 3.2.8 on 2021-10-13 08:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211013_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='clothing_sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='XS', max_length=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_properties',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SS', 'sterling silver'), ('GP', 'gold plated'), ('PW', 'wool'), ('HC', 'hand crafted'), ('FP', 'fairly produced'), ('LI', 'low environmental impact')], default='FP', max_length=11),
        ),
        migrations.AlterField(
            model_name='ring',
            name='ring_sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('6', 'L'), ('7', 'N'), ('8', 'P'), ('9', 'S'), ('10', 'U')], default='6', max_length=11),
        ),
    ]
