# Generated by Django 3.2.8 on 2021-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211013_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_type',
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_size_matrix',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='one_size',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ring_size_matrix',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
